### ISSUE TITLE
添加IOS平台时提示找不到libs/EZDemoSDKResources.bundle

### ISSUE THREAD

**Issue by yoli799480165** [plotozhu/cordova-plugin-ezviz#1]
不知道目前进度怎么样？IOS插件可以使用吗？
添加IOS插件时报错：
Installing "cordova-plugin-ezviz" for ios
Error during processing of action! Attempting to revert...
Cannot find resource file "/Users/Cenyong/Desktop/projects/fbox-mobile/plugins/cordova-plugin-ezviz/libs/EZDemoSDKResources.bundle" for plugin cordova-plugin-ezviz in iOS platform
以及
Cannot find framework "/Users/Cenyong/Desktop/projects/fbox-mobile/plugins/cordova-plugin-ezviz/libs/EZDemoSDK.framework"
由于缺少资源文件目前无法编译通过，能处理下吗？

**Comment by MrMessy77** [comment]
ios的插件目前在开发中，敬请期待
